-- ============================================================
-- SCHÉMA COMPLET SUPABASE - N&H Love App
-- Copie tout ce bloc dans l'éditeur SQL de Supabase
-- ============================================================

-- 1. PROFILES (extension de auth.users)
CREATE TABLE profiles (
  id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  username TEXT,
  avatar_url TEXT,
  created_at TIMESTAMPTZ DEFAULT now()
);

ALTER TABLE profiles ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Les deux peuvent lire leurs profils"
  ON profiles FOR SELECT
  USING (auth.role() = 'authenticated');

CREATE POLICY "Chacun peut modifier son profil"
  ON profiles FOR UPDATE
  USING (auth.uid() = id);

-- Fonction pour créer auto un profil à l'inscription
CREATE OR REPLACE FUNCTION handle_new_user()
RETURNS TRIGGER AS $$
BEGIN
  INSERT INTO profiles (id, username)
  VALUES (NEW.id, split_part(NEW.email, '@', 1));
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE FUNCTION handle_new_user();


-- 2. MESSAGES
CREATE TABLE messages (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
  author TEXT NOT NULL DEFAULT 'Anonyme',
  text TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT now()
);

ALTER TABLE messages ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Les deux peuvent lire tous les messages"
  ON messages FOR SELECT
  USING (auth.role() = 'authenticated');

CREATE POLICY "Chacun peut créer un message"
  ON messages FOR INSERT
  WITH CHECK (auth.role() = 'authenticated');

CREATE POLICY "Chacun peut supprimer ses propres messages"
  ON messages FOR DELETE
  USING (auth.uid() = user_id);


-- 3. PHOTOS
CREATE TABLE photos (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
  caption TEXT DEFAULT '',
  storage_path TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT now()
);

ALTER TABLE photos ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Les deux peuvent voir toutes les photos"
  ON photos FOR SELECT
  USING (auth.role() = 'authenticated');

CREATE POLICY "Chacun peut ajouter une photo"
  ON photos FOR INSERT
  WITH CHECK (auth.role() = 'authenticated');

CREATE POLICY "Chacun peut supprimer ses photos"
  ON photos FOR DELETE
  USING (auth.uid() = user_id);


-- 4. DESSINS
CREATE TABLE drawings (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
  data_url TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT now()
);

ALTER TABLE drawings ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Les deux peuvent voir tous les dessins"
  ON drawings FOR SELECT
  USING (auth.role() = 'authenticated');

CREATE POLICY "Chacun peut ajouter un dessin"
  ON drawings FOR INSERT
  WITH CHECK (auth.role() = 'authenticated');

CREATE POLICY "Chacun peut supprimer ses dessins"
  ON drawings FOR DELETE
  USING (auth.uid() = user_id);


-- 5. QUESTIONS (Vérité ou Action)
CREATE TABLE questions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  type TEXT NOT NULL CHECK (type IN ('truth', 'dare')),
  question TEXT NOT NULL,
  difficulty TEXT NOT NULL CHECK (difficulty IN ('soft', 'medium', 'hot')),
  created_by UUID REFERENCES auth.users(id),
  created_at TIMESTAMPTZ DEFAULT now()
);

ALTER TABLE questions ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Les deux peuvent lire toutes les questions"
  ON questions FOR SELECT
  USING (auth.role() = 'authenticated');

CREATE POLICY "Les deux peuvent ajouter des questions"
  ON questions FOR INSERT
  WITH CHECK (auth.role() = 'authenticated');


-- 6. QUESTIONS PRÉREMPLIES
INSERT INTO questions (type, question, difficulty) VALUES
-- SOFT TRUTHS
('truth', 'Quel est ton plus beau souvenir avec moi ?', 'soft'),
('truth', 'Qu''est-ce que tu as pensé la première fois qu''on s''est vus ?', 'soft'),
('truth', 'Quelle est ta qualité préférée chez moi ?', 'soft'),
('truth', 'Quel est ton petit surnom secret pour moi ?', 'soft'),
('truth', 'Quelle est notre chanson ?', 'soft'),
('truth', 'Qu''est-ce qui te fait sourire quand tu penses à nous ?', 'soft'),
('truth', 'Quel est le meilleur cadeau que je t''ai offert ?', 'soft'),
('truth', 'Où est-ce que tu voudrais qu''on aille en voyage ensemble ?', 'soft'),
('truth', 'Quel film tu veux absolument regarder avec moi ?', 'soft'),
('truth', 'Qu''est-ce que tu aimes le plus chez nous en tant que couple ?', 'soft'),
-- SOFT DARES
('dare', 'Envoie-moi un message vocal qui dit "je t''aime" de 3 façons différentes', 'soft'),
('dare', 'Dessine mon portrait en 30 secondes et envoie-le moi', 'soft'),
('dare', 'Chante notre chanson préférée et envoie un audio', 'soft'),
('dare', 'Prends un selfie avec une moue et envoie-le', 'soft'),
('dare', 'Raconte une blague nulle en story Instagram', 'soft'),
('dare', 'Écris un poème de 2 lignes sur nous', 'soft'),
('dare', 'Fais un vœu et souffle une bougie en pensant à nous', 'soft'),
-- MEDIUM TRUTHS
('truth', 'Quel est ton fantasme le plus doux ?', 'medium'),
('truth', 'Qu''est-ce qui t''excite chez moi ?', 'medium'),
('truth', 'Quel est le moment le plus romantique de notre relation ?', 'medium'),
('truth', 'Qu''est-ce que tu voudrais qu''on essaie ensemble ?', 'medium'),
('truth', 'Quelle partie de mon corps tu préfères ?', 'medium'),
('truth', 'Quel est ton souvenir le plus "chaud" avec moi ?', 'medium'),
('truth', 'Qu''est-ce que tu penses vraiment des longues distances ?', 'medium'),
('truth', 'À quoi tu penses quand tu es seul(e) le soir ?', 'medium'),
-- MEDIUM DARES
('dare', 'Envoie-moi une photo de ce que tu portes maintenant', 'medium'),
('dare', 'Écris-moi un texto coquin de 2 phrases', 'medium'),
('dare', 'Fais-moi une déclaration en vidéo (30 sec min)', 'medium'),
('dare', 'Envoie un audio avec ta voix la plus sensuelle en chuchotant mon prénom', 'medium'),
('dare', 'Porte quelque chose de sexy et envoie une photo', 'medium'),
('dare', 'Décris en détail ce que tu ferais si j''étais là maintenant', 'medium'),
-- HOT TRUTHS
('truth', 'Quel est ton fantasme le plus fou ?', 'hot'),
('truth', 'Qu''est-ce que tu voudrais qu''on fasse qu''on a jamais fait ?', 'hot'),
('truth', 'Raconte ton rêve érotique préféré', 'hot'),
('truth', 'Qu''est-ce qui te rend le/la plus excité(e) chez moi ?', 'hot'),
('truth', 'Où est l''endroit le plus audacieux où tu voudrais qu''on le fasse ?', 'hot'),
('truth', 'Quelle est la chose la plus coquine que tu aies imaginée avec moi ?', 'hot'),
('truth', 'Quel rôle tu voudrais qu''on joue ensemble ?', 'hot'),
('truth', 'Quel est ton plus grand désir inavoué ?', 'hot'),
-- HOT DARES
('dare', 'Envoie-moi une photo suggestive sans montrer ton visage', 'hot'),
('dare', 'Écris un scénario érotique de 5 lignes avec nous', 'hot'),
('dare', 'Envoie un message vocal coquin de 30 secondes', 'hot'),
('dare', 'Prends une photo de toi avec un accessoire "spécial"', 'hot'),
('dare', 'Décris en détail ce que tu veux qu''on fasse aux prochaines retrouvailles', 'hot'),
('dare', 'Envoie-moi un "bonjour" très coquin par message', 'hot');
