-- Table pour synchroniser le morpion entre les deux joueurs
CREATE TABLE IF NOT EXISTS game_morpion (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  room_id BIGINT REFERENCES rooms(id) ON DELETE CASCADE,
  board JSONB DEFAULT '[]'::jsonb,
  x_is_next BOOLEAN DEFAULT true,
  scores JSONB DEFAULT '{"💕":0,"❤️":0}'::jsonb,
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now()
);
ALTER TABLE game_morpion ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Public game_morpion" ON game_morpion;
CREATE POLICY "Public game_morpion" ON game_morpion FOR ALL USING (true) WITH CHECK (true);
