-- ============================================================
-- SCHÉMA SUPABASE - N&H Love App (ACCÈS PUBLIC)
-- Exécute tout ce bloc dans l'éditeur SQL Supabase
-- ============================================================

-- 1. MESSAGES
CREATE TABLE IF NOT EXISTS messages (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  author TEXT NOT NULL DEFAULT 'Anonyme',
  text TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT now()
);

ALTER TABLE messages ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Public acces messages" ON messages;
CREATE POLICY "Public acces messages"
  ON messages FOR ALL
  USING (true)
  WITH CHECK (true);

-- 2. PHOTOS
CREATE TABLE IF NOT EXISTS photos (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  caption TEXT DEFAULT '',
  storage_path TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT now()
);

ALTER TABLE photos ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Public acces photos" ON photos;
CREATE POLICY "Public acces photos"
  ON photos FOR ALL
  USING (true)
  WITH CHECK (true);

-- 3. DESSINS
CREATE TABLE IF NOT EXISTS drawings (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  data_url TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT now()
);

ALTER TABLE drawings ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Public acces drawings" ON drawings;
CREATE POLICY "Public acces drawings"
  ON drawings FOR ALL
  USING (true)
  WITH CHECK (true);

-- 4. QUESTIONS (Vérité ou Action)
CREATE TABLE IF NOT EXISTS questions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  type TEXT NOT NULL CHECK (type IN ('truth', 'dare')),
  question TEXT NOT NULL,
  difficulty TEXT NOT NULL CHECK (difficulty IN ('soft', 'medium', 'hot')),
  created_at TIMESTAMPTZ DEFAULT now()
);

ALTER TABLE questions ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Public acces questions" ON questions;
CREATE POLICY "Public acces questions"
  ON questions FOR ALL
  USING (true)
  WITH CHECK (true);

-- 5. QUESTIONS PRÉREMPLIES (optionnel - exécute une fois)
INSERT INTO questions (type, question, difficulty)
SELECT * FROM (VALUES
  ('truth', 'Quel est ton plus beau souvenir avec moi ?', 'soft'),
  ('truth', 'Qu''est-ce que tu as pensé la première fois qu''on s''est vus ?', 'soft'),
  ('truth', 'Quelle est ta qualité préférée chez moi ?', 'soft'),
  ('truth', 'Quel est ton petit surnom secret pour moi ?', 'soft'),
  ('truth', 'Quelle est notre chanson ?', 'soft'),
  ('truth', 'Qu''est-ce qui te fait sourire quand tu penses à nous ?', 'soft'),
  ('truth', 'Quel est le meilleur cadeau que je t''ai offert ?', 'soft'),
  ('truth', 'Où est-ce que tu voudrais qu''on aille en voyage ensemble ?', 'soft'),
  ('truth', 'Quel film tu veux absolument regarder avec moi ?', 'soft'),
  ('truth', 'Qu''est-ce que tu aimes le plus chez nous en tant que couple ?', 'soft'),
  ('dare', 'Envoie-moi un message vocal qui dit "je t''aime" de 3 façons différentes', 'soft'),
  ('dare', 'Dessine mon portrait en 30 secondes et envoie-le moi', 'soft'),
  ('dare', 'Chante notre chanson préférée et envoie un audio', 'soft'),
  ('dare', 'Prends un selfie avec une moue et envoie-le', 'soft'),
  ('dare', 'Raconte une blague nulle en story Instagram', 'soft'),
  ('dare', 'Écris un poème de 2 lignes sur nous', 'soft'),
  ('dare', 'Fais un vœu et souffle une bougie en pensant à nous', 'soft'),
  ('truth', 'Quel est ton fantasme le plus doux ?', 'medium'),
  ('truth', 'Qu''est-ce qui t''excite chez moi ?', 'medium'),
  ('truth', 'Quel est le moment le plus romantique de notre relation ?', 'medium'),
  ('truth', 'Qu''est-ce que tu voudrais qu''on essaie ensemble ?', 'medium'),
  ('truth', 'Quelle partie de mon corps tu préfères ?', 'medium'),
  ('truth', 'Quel est ton souvenir le plus "chaud" avec moi ?', 'medium'),
  ('truth', 'Qu''est-ce que tu penses vraiment des longues distances ?', 'medium'),
  ('truth', 'À quoi tu penses quand tu es seul(e) le soir ?', 'medium'),
  ('dare', 'Envoie-moi une photo de ce que tu portes maintenant', 'medium'),
  ('dare', 'Écris-moi un texto coquin de 2 phrases', 'medium'),
  ('dare', 'Fais-moi une déclaration en vidéo (30 sec min)', 'medium'),
  ('dare', 'Envoie un audio avec ta voix la plus sensuelle en chuchotant mon prénom', 'medium'),
  ('dare', 'Porte quelque chose de sexy et envoie une photo', 'medium'),
  ('dare', 'Décris en détail ce que tu ferais si j''étais là maintenant', 'medium'),
  ('truth', 'Quel est ton fantasme le plus fou ?', 'hot'),
  ('truth', 'Qu''est-ce que tu voudrais qu''on fasse qu''on a jamais fait ?', 'hot'),
  ('truth', 'Raconte ton rêve érotique préféré', 'hot'),
  ('truth', 'Qu''est-ce qui te rend le/la plus excité(e) chez moi ?', 'hot'),
  ('truth', 'Où est l''endroit le plus audacieux où tu voudrais qu''on le fasse ?', 'hot'),
  ('truth', 'Quelle est la chose la plus coquine que tu aies imaginée avec moi ?', 'hot'),
  ('truth', 'Quel rôle tu voudrais qu''on joue ensemble ?', 'hot'),
  ('truth', 'Quel est ton plus grand désir inavoué ?', 'hot'),
  ('dare', 'Envoie-moi une photo suggestive sans montrer ton visage', 'hot'),
  ('dare', 'Écris un scénario érotique de 5 lignes avec nous', 'hot'),
  ('dare', 'Envoie un message vocal coquin de 30 secondes', 'hot'),
  ('dare', 'Prends une photo de toi avec un accessoire "spécial"', 'hot'),
  ('dare', 'Décris en détail ce que tu veux qu''on fasse aux prochaines retrouvailles', 'hot'),
  ('dare', 'Envoie-moi un "bonjour" très coquin par message', 'hot')
) AS v(type, question, difficulty)
WHERE NOT EXISTS (SELECT 1 FROM questions LIMIT 1);
