-- Exécute ceci DANS L'ORDRE dans Supabase SQL Editor

-- Supprimer les anciennes tables
DROP TABLE IF EXISTS drawings CASCADE;
DROP TABLE IF EXISTS photos CASCADE;
DROP TABLE IF EXISTS messages CASCADE;
DROP TABLE IF EXISTS questions CASCADE;
DROP TABLE IF EXISTS rooms CASCADE;

-- Table ROOMS
CREATE TABLE rooms (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code TEXT UNIQUE NOT NULL,
  name1 TEXT DEFAULT 'Toi',
  name2 TEXT DEFAULT 'Lui/Elle',
  start_date DATE DEFAULT '2024-01-15',
  next_meeting DATE DEFAULT '2026-08-15',
  city1_name TEXT DEFAULT 'Paris',
  city1_lat DOUBLE PRECISION DEFAULT 48.8566,
  city1_lng DOUBLE PRECISION DEFAULT 2.3522,
  city2_name TEXT DEFAULT 'Los Angeles',
  city2_lat DOUBLE PRECISION DEFAULT 34.0522,
  city2_lng DOUBLE PRECISION DEFAULT -118.2437,
  created_at TIMESTAMPTZ DEFAULT now()
);
ALTER TABLE rooms ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public rooms" ON rooms FOR ALL USING (true) WITH CHECK (true);

-- MESSAGES
CREATE TABLE messages (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  room_id BIGINT REFERENCES rooms(id) ON DELETE CASCADE,
  author TEXT NOT NULL DEFAULT 'Anonyme',
  text TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT now()
);
ALTER TABLE messages ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public messages" ON messages FOR ALL USING (true) WITH CHECK (true);

-- MESSAGES : ajout colonne image
ALTER TABLE messages ADD COLUMN IF NOT EXISTS image_url TEXT;

-- PHOTOS
CREATE TABLE IF NOT EXISTS photos (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  room_id BIGINT REFERENCES rooms(id) ON DELETE CASCADE,
  caption TEXT DEFAULT '',
  storage_path TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT now()
);
ALTER TABLE photos ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename='photos' AND policyname='Public photos') THEN
    CREATE POLICY "Public photos" ON photos FOR ALL USING (true) WITH CHECK (true);
  END IF;
END $$;

-- NOTIFICATIONS
CREATE TABLE IF NOT EXISTS notifications (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  room_id BIGINT REFERENCES rooms(id) ON DELETE CASCADE,
  type TEXT NOT NULL,
  message TEXT NOT NULL,
  author TEXT DEFAULT '',
  read BOOLEAN DEFAULT false,
  created_at TIMESTAMPTZ DEFAULT now()
);
ALTER TABLE notifications ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename='notifications' AND policyname='Public notifications') THEN
    CREATE POLICY "Public notifications" ON notifications FOR ALL USING (true) WITH CHECK (true);
  END IF;
END $$;

-- DESSINS
CREATE TABLE drawings (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  room_id BIGINT REFERENCES rooms(id) ON DELETE CASCADE,
  data_url TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT now()
);
ALTER TABLE drawings ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public drawings" ON drawings FOR ALL USING (true) WITH CHECK (true);

-- QUESTIONS
CREATE TABLE questions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  type TEXT NOT NULL CHECK (type IN ('truth', 'dare')),
  question TEXT NOT NULL,
  difficulty TEXT NOT NULL CHECK (difficulty IN ('soft', 'medium', 'hot')),
  created_at TIMESTAMPTZ DEFAULT now()
);
ALTER TABLE questions ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public questions" ON questions FOR ALL USING (true) WITH CHECK (true);

-- Questions préremplies (exécute UNE SEULE FOIS)
INSERT INTO questions (type, question, difficulty)
SELECT * FROM (VALUES
  ('truth','Quel est ton plus beau souvenir avec moi ?','soft'),
  ('truth','Qu''est-ce que tu as pensé la première fois qu''on s''est vus ?','soft'),
  ('truth','Quelle est ta qualité préférée chez moi ?','soft'),
  ('truth','Quel est ton petit surnom secret pour moi ?','soft'),
  ('truth','Quelle est notre chanson ?','soft'),
  ('truth','Qu''est-ce qui te fait sourire quand tu penses à nous ?','soft'),
  ('truth','Quel est le meilleur cadeau que je t''ai offert ?','soft'),
  ('truth','Où est-ce que tu voudrais qu''on aille en voyage ensemble ?','soft'),
  ('truth','Qu''est-ce que tu aimes le plus chez nous en tant que couple ?','soft'),
  ('dare','Envoie-moi un message vocal qui dit "je t''aime" de 3 façons différentes','soft'),
  ('dare','Dessine mon portrait en 30 secondes et envoie-le moi','soft'),
  ('dare','Chante notre chanson préférée et envoie un audio','soft'),
  ('dare','Prends un selfie avec une moue et envoie-le','soft'),
  ('dare','Écris un poème de 2 lignes sur nous','soft'),
  ('dare','Fais un vœu et souffle une bougie en pensant à nous','soft'),
  ('truth','Quel est ton fantasme le plus doux ?','medium'),
  ('truth','Qu''est-ce qui t''excite chez moi ?','medium'),
  ('truth','Quel est le moment le plus romantique de notre relation ?','medium'),
  ('truth','Qu''est-ce que tu voudrais qu''on essaie ensemble ?','medium'),
  ('truth','Quelle partie de mon corps tu préfères ?','medium'),
  ('truth','Quel est ton souvenir le plus "chaud" avec moi ?','medium'),
  ('truth','Qu''est-ce que tu penses vraiment des longues distances ?','medium'),
  ('truth','À quoi tu penses quand tu es seul(e) le soir ?','medium'),
  ('dare','Envoie-moi une photo de ce que tu portes maintenant','medium'),
  ('dare','Écris-moi un texto coquin de 2 phrases','medium'),
  ('dare','Fais-moi une déclaration en vidéo (30 sec min)','medium'),
  ('dare','Envoie un audio avec ta voix la plus sensuelle en chuchotant mon prénom','medium'),
  ('dare','Porte quelque chose de sexy et envoie une photo','medium'),
  ('dare','Décris en détail ce que tu ferais si j''étais là maintenant','medium'),
  ('truth','Quel est ton fantasme le plus fou ?','hot'),
  ('truth','Qu''est-ce que tu voudrais qu''on fasse qu''on a jamais fait ?','hot'),
  ('truth','Raconte ton rêve érotique préféré','hot'),
  ('truth','Qu''est-ce qui te rend le/la plus excité(e) chez moi ?','hot'),
  ('truth','Où est l''endroit le plus audacieux où tu voudrais qu''on le fasse ?','hot'),
  ('truth','Quelle est la chose la plus coquine que tu aies imaginée avec moi ?','hot'),
  ('truth','Quel rôle tu voudrais qu''on joue ensemble ?','hot'),
  ('truth','Quel est ton plus grand désir inavoué ?','hot'),
  ('dare','Envoie-moi une photo suggestive sans montrer ton visage','hot'),
  ('dare','Écris un scénario érotique de 5 lignes avec nous','hot'),
  ('dare','Envoie un message vocal coquin de 30 secondes','hot'),
  ('dare','Prends une photo de toi avec un accessoire "spécial"','hot'),
  ('dare','Décris en détail ce que tu veux qu''on fasse aux prochaines retrouvailles','hot'),
  ('dare','Envoie-moi un "bonjour" très coquin par message','hot'),
  -- + SOFT
  ('truth','Quel est ton plat préféré que je cuisine ?','soft'),
  ('truth','Quelle est la première chose que tu regardes chez moi le matin ?','soft'),
  ('truth','Qu''est-ce qui te manque le plus quand on est loin ?','soft'),
  ('truth','Quel est notre meilleur fou rire ensemble ?','soft'),
  ('truth','Si tu pouvais revenir à un moment, lequel ?','soft'),
  ('truth','Qu''est-ce que tu veux qu''on fasse absolument ensemble ?','soft'),
  ('truth','Quel mot doux tu préfères que je te dise ?','soft'),
  ('truth','Décris notre relation en 3 mots','soft'),
  ('truth','Si on était un film, lequel serait-ce ?','soft'),
  ('truth','Où te vois-tu dans 5 ans avec moi ?','soft'),
  ('dare','Fais-nous un story-time de 30 sec sur notre meilleur moment','soft'),
  ('dare','Dessine un cœur sur ta main et prends une photo','soft'),
  ('dare','Envoie un message à mon meilleur pote pour lui dire que tu m''aimes','soft'),
  ('dare','Mime notre première rencontre en vidéo','soft'),
  ('dare','Récite un poème d''amour improvisé de 10 secondes','soft'),
  -- + MEDIUM
  ('truth','Qu''est-ce qui t''a fait craquer sur moi au début ?','medium'),
  ('truth','Quelle est la chose la plus romantique que j''ai faite ?','medium'),
  ('truth','Quelle est ta plus grande peur dans notre couple ?','medium'),
  ('truth','Quel est le moment où tu as le plus eu envie de moi ?','medium'),
  ('truth','Qu''est-ce que tu n''oses pas me dire en face ?','medium'),
  ('truth','Qu''est-ce qui t''excite le plus chez moi physiquement ?','medium'),
  ('truth','Décris notre premier baiser en détail','medium'),
  ('dare','Écris-nous un scénario de 3 lignes sur nos retrouvailles parfaites','medium'),
  ('dare','Porte UNIQUEMENT mon t-shirt préféré et envoie une photo','medium'),
  ('dare','Chuchote-moi quelque chose de doux à l''oreille en audio','medium'),
  ('dare','Fais un vlog de 1 min sur ce que tu ferais si j''étais là maintenant','medium'),
  ('dare','Écris un SMS coquin comme si tu venais de te réveiller à côté de moi','medium'),
  ('dare','Décris en détail ton plus beau fantasme de nous deux','medium'),
  -- + HOT
  ('truth','Quel est ton plus grand tabou sexuel ?','hot'),
  ('truth','Qu''est-ce que tu voudrais essayer absolument une fois ?','hot'),
  ('truth','Quelle est la partie de mon corps qui te rend le plus fou/folle ?','hot'),
  ('truth','À quelle fréquence penses-tu à moi de façon coquine ?','hot'),
  ('truth','Quel est ton souvenir érotique préféré avec moi ?','hot'),
  ('truth','Qu''est-ce qui te ferait lâcher tout contrôle ?','hot'),
  ('truth','Quel est ton fantasme ultime avec moi ?','hot'),
  ('truth','Décris exactement ce que tu veux qu''on se fasse aux prochaines retrouvailles','hot'),
  ('dare','Décris en détail ton scénario érotique parfait avec moi (5 lignes minimum)','hot'),
  ('dare','Écris un court récit érotique où on est les héros (8 lignes)','hot'),
  ('dare','Fais un audio de 20 secondes avec tes bruits les plus sensuels','hot'),
  ('dare','Décris exactement comment tu veux que je te touche','hot'),
  ('dare','Invente un jeu entre nous et décris les règles coquines','hot')
) AS v
WHERE NOT EXISTS (SELECT 1 FROM questions);

-- QUIZ SESSIONS
CREATE TABLE IF NOT EXISTS quiz_sessions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  room_id BIGINT REFERENCES rooms(id) ON DELETE CASCADE,
  creator TEXT NOT NULL,
  questions JSONB NOT NULL,
  creator_answers JSONB,
  partner_answers JSONB,
  score INTEGER DEFAULT 0,
  completed BOOLEAN DEFAULT false,
  created_at TIMESTAMPTZ DEFAULT now()
);
ALTER TABLE quiz_sessions ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename='quiz_sessions' AND policyname='Public quiz_sessions') THEN
    CREATE POLICY "Public quiz_sessions" ON quiz_sessions FOR ALL USING (true) WITH CHECK (true);
  END IF;
END $$;

-- PHOTO COMMENTS
CREATE TABLE IF NOT EXISTS photo_comments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  photo_id BIGINT REFERENCES photos(id) ON DELETE CASCADE,
  room_id BIGINT REFERENCES rooms(id) ON DELETE CASCADE,
  author TEXT NOT NULL,
  text TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT now()
);
ALTER TABLE photo_comments ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename='photo_comments' AND policyname='Public photo_comments') THEN
    CREATE POLICY "Public photo_comments" ON photo_comments FOR ALL USING (true) WITH CHECK (true);
  END IF;
END $$;

-- DAILY QUESTIONS LOG
CREATE TABLE IF NOT EXISTS daily_answers (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  room_id BIGINT REFERENCES rooms(id) ON DELETE CASCADE,
  date DATE NOT NULL,
  question TEXT NOT NULL,
  answer TEXT DEFAULT '',
  author TEXT DEFAULT '',
  created_at TIMESTAMPTZ DEFAULT now()
);
ALTER TABLE daily_answers ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename='daily_answers' AND policyname='Public daily_answers') THEN
    CREATE POLICY "Public daily_answers" ON daily_answers FOR ALL USING (true) WITH CHECK (true);
  END IF;
END $$;
